require: rubocop-rspec

AllCops:
  DefaultFormatter: fuubar
  TargetRubyVersion: 2.3
  DisplayCopNames: true

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - afk.gemspec
    - spec/**/*_spec.rb

RSpec/MultipleExpectations:
  Enabled: false

RSpec/ExampleLength:
  Max: 25

Naming/VariableNumber:
  EnforcedStyle: snake_case

# default disabled rules
Style/AutoResourceCleanup:
  Enabled: true

Style/CollectionMethods:
  Enabled: true
  PreferredMethods:
    collect: 'map'
    collect!: 'map!'
    inject: 'reduce'
    find: 'detect'
    find_all: 'select'

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Layout/FirstArrayElementLineBreak:
  Enabled: true

Layout/FirstHashElementLineBreak:
  Enabled: true

Layout/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/FirstMethodParameterLineBreak:
  Enabled: true

Layout/MultilineArrayBraceLayout:
  Enabled: true

Layout/MultilineHashBraceLayout:
  Enabled: true

Layout/MultilineMethodCallBraceLayout:
  Enabled: true

Layout/MultilineMethodDefinitionBraceLayout:
  Enabled: true

Style/OptionHash:
  Enabled: true

Style/Send:
  Enabled: true

RSpec/VerifiedDoubles:
  Enabled: true

# non-conventional rules
Style/LambdaCall:
  EnforcedStyle: braces

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/AccessModifierIndentation:
  EnforcedStyle: outdent

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
