#!/usr/bin/env ruby
# frozen_string_literal: true

require_relative '../lib/afk'

output_index = ARGV.index('-o')
output =
  if output_index
    File.open(ARGV[output_index + 1], 'w')
  else
    STDOUT
  end
AFK::Runner.new(output: output).()
